apiVersion: v1
kind: Service
metadata:
  name: vscode
spec:
  selector:
    app: vscode
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  externalTrafficPolicy: Cluster
